In [4]:
#1>AlexandreTheophile Vandermonde matrix
import numpy as np

In [5]:
m = np.array([1, 2, 3, 5])
m

array([1, 2, 3, 5])

In [6]:
def vandermonde(arr, N=None, increasing=False):
    if N == None:
        N = len(arr)

    out = np.zeros((len(arr), N))
    
    for i in range(out.shape[0]):
        for j in range(N):
            if increasing == False:
                out[i, j] = arr[i]**(N - j - 1)
            else:
                out[i, j] = arr[i]**(j)
    return out

In [7]:
print("self-made function:\n" + str(vandermonde(m, increasing=True)) + "\nbuilt-in numpy function:\n" + str(np.vander(m, increasing=True)))

self-made function:
[[  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   5.  25. 125.]]
built-in numpy function:
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


In [8]:
# 2> Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

def moving_average(arr, window):
    n = len(arr)
    mov_avg = []
    for i in range(n - window + 1):
        curr_window_avg = np.mean(arr[i : i + window])
        mov_avg.append(curr_window_avg)
        print('y' + str(i) + ' = ' + str(curr_window_avg))
    return mov_avg
        

In [9]:
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window = 3
moving_average(arr, window)

y0 = 5.0
y1 = 4.666666666666667
y2 = 5.666666666666667
y3 = 6.666666666666667
y4 = 9.666666666666666
y5 = 28.666666666666668
y6 = 49.333333333333336
y7 = 72.66666666666667
y8 = 84.0
y9 = 93.33333333333333
y10 = 116.33333333333333


[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]